name: vendor_x_ai
description: "VendorX AI - AI assistant for Indian Kirana stores."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # The Brain: Reasoning & Multimodal AI
  google_generative_ai: ^0.4.5 
  # The Ears: Voice Interface
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2
  # The Eyes: Visual Recognition
  camera: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0
  # The Action: Automated Reminders & Storage
  whatsapp_cloud_flutter: ^1.1.2
  isar: ^3.1.0+1 # For the Digital Khata database
  google_fonts: ^8.0.0
  uuid: ^4.5.2
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/